<%@ page language="java" contentType="text/html; charset=GB18030"
    pageEncoding="GB18030"%>
<div id="dialog-form" title="新增员工">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td width="8" background="../images/tab_12.gif">
			&nbsp;
		</td>
		<td>
			<table width="100%" border="0" cellpadding="0" cellspacing="1"
				bgcolor="b5d6e6" onmouseover="changeto()" onmouseout="changeback()">
				<!-- 
				<tr>
					<td width="3%" height="22" background="../images/bg1.gif"
						bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox" value="checkbox" />
						</div>
					</td>
					<td width="3%" height="22" background="../images/bg1.gif"
						bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">序号</span>
						</div>
					</td>
					<td width="12%" height="22" background="../images/bg1.gif"
						bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">接收号码</span>
						</div>
					</td>
					<td width="14%" height="22" background="../images/bg1.gif"
						bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">发送时间</span>
						</div>
					</td>
					<td width="18%" background="../images/bg1.gif" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">邮件地址</span>
						</div>
					</td>
					<td width="23%" height="22" background="../images/bg1.gif"
						bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">内容</span>
						</div>
					</td>
					<td width="15%" height="22" background="../images/bg1.gif"
						bgcolor="#FFFFFF" class="STYLE1">
						<div align="center">
							基本操作
						</div>
					</td>
				</tr>
				-->
				<tr>
					<!-- 
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox2" value="checkbox" />
						</div>
					</td>
					 -->
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								姓名
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<!-- 
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
					-->
				</tr>
				<!-- 
				<tr>
					<!--
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox3" value="checkbox" />
						</div>
					</td>
					-->
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								02
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox4" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								03
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox5" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								04
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox6" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								05
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox7" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								06
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox8" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								07
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox9" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								08
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox10" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								09
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox11" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								10
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox12" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								11
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox13" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								12
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox14" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								13
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox15" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								14
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				<tr>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<input type="checkbox" name="checkbox16" value="checkbox" />
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center" class="STYLE1">
							<div align="center">
								15
							</div>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">13813916585</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">2007-11-16 15:00:20 </span>
						</div>
					</td>
					<td bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">tiezhu0902@163.com</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE1">南京科技股份有限公司…</span>
						</div>
					</td>
					<td height="20" bgcolor="#FFFFFF">
						<div align="center">
							<span class="STYLE4"><img src="../images/edt.gif"
									width="16" height="16" />编辑&nbsp; &nbsp;<img
									src="../images/del.gif" width="16" height="16" />删除</span>
						</div>
					</td>
				</tr>
				 -->
			</table>
		</td>
		<td width="8" background="../images/tab_15.gif">
			&nbsp;
		</td>
	</tr>
</table>
</div>